### PR TITLE
fix ruby 2.4 Fixnum deprecations

### LINKED ISSUE #289: Replace Fixnum with Integer to fix ruby 2.4 deprecations
[Fixnum & Bignum are now Integer](https://www.ruby-lang.org/en/news/2016/12/25/ruby-2-4-0-released/)

```
ruby-2.4.0/gems/neo4j-core-7.0.6/lib/neo4j/property_validator.rb:8: warning: constant ::Fixnum is deprecated
```

### PR DESCRIPTION
**Pull request by jboler**
Fixes #289 

This pull introduces/changes:
 * Substitutes Integer for Fixnum
 * Retains Ruby <=2.3 compatibility

Pings:
@cheerfulstoic
@subvertallchris

### CODE REVIEW

File: spec/shared_examples/node_with_tx.rb [hunk 1]
```diff
@@ -2,7 +2,7 @@
   shared_examples 'a node with properties and id' do
     describe '#neo_id' do
       it 'is a fixnum' do
-        expect(subject.neo_id).to be_a(Fixnum)
+        expect(subject.neo_id).to be_a(Integer)
```
Comment (koic) [inline spec/shared_examples/node_with_tx.rb]: It can use `be_an` instead of `be_a`.

https://github.com/rspec/rspec-expectations/blob/v3.5.0/lib/rspec/matchers.rb#L361-L365

**Comment by cheerfulstoic** [comment]
Awesome thanks!  Released as 7.0.7
