### PR TITLE
Fixing BOLT adaptor bugs

### LINKED ISSUE #269: BOLT adaptor crashes when creating nodes with a very big payload
When running queries with very large parameters using BOLT, neo4j-core fails to run it, and breaks the current session, requiring to reconnect to continue making queries.

### Code example (inline, gist, or repo)

```ruby
adaptor.query(session, 'CREATE (n:Test) SET n = {props} RETURN n', props: {text: 'a' * 10_000})
# RuntimeError:
# Making query, but expected there to be no buffer remaining!
```

### Runtime information:

Neo4j database version: any
`neo4j-core` gem version: 7.0.0

### PR DESCRIPTION
**Pull request by ProGM**
Fixes #269

This pull introduces/changes:
 * Improves error handling and debug messages for BOLT
 * Avoids this exception:
```
     # NoMethodError:
     #   undefined method `[]' for nil:NilClass
     #   ./lib/neo4j/core/cypher_session/responses/bolt.rb:68:in `block in extract_message_groups'
```

That was indirectly causing #269

Pings:
@cheerfulstoic
@subvertallchris

### CODE REVIEW

File: lib/neo4j/core/cypher_session/responses/bolt.rb [hunk 1]
```diff
@@ -52,10 +52,16 @@ def wrap_entity(entity_data)
...
+
             validate_message_type!(fields_messages[0], :success)
 
             result_messages = []
-            while (messages = flush_messages_proc.call)[0].type != :success
+            messages = nil
+
+            loop do
+              messages = flush_messages_proc.call
+              next if messages.nil?
```
Comment (ProGM) [inline lib/neo4j/core/cypher_session/responses/bolt.rb]: @cheerfulstoic This is pretty critical. This line avoids the bug, but I need confirmation.

Can you take a look?

Comment (cheerfulstoic) [inline lib/neo4j/core/cypher_session/responses/bolt.rb]: Interesting....  I think we must get this when the server returns something in the socket but without any data.  Otherwise I think we would just sit listening to the socket and eventually time out.

So I *think* that this is fine.  If it works in the specs and if it works in your app then we should merge it and I'll try it in our app.

**Comment by ProGM** [comment]
This seems to work in my app, too! Merging 😜
